version: "3.3"
services:
  viyaapp:
    build: .
    restart: always
    ports:
      - 5000:8080
    environment: 
      - VIYA_SERVER=
      - DEBUG=

  # Mounts volumes as needed
  # volumes:
  #   - c:/Public/dev/data/sas:/sasin